export default [
  {
    id: 1,
    postedOn: "2024-10-28",
    title: "iOS Developer",
    company: "Apple",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["SwiftUI", "UIKit", "Core Data"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    id: 2,
    postedOn: "2024-10-24",
    title: "Frontend Developer",
    company: "Amazon",
    type: "Full Time",
    experience: "Fresher",
    location: "In-Office",
    skills: ["JavaScript", "Next.js", "React"],
    job_link: "https://www.amazon.jobs/en/",
  },
  {
    id: 3,
    postedOn: "2024-10-20",
    title: "Backend Developer",
    company: "Google",
    type: "Full Time",
    experience: "Senior Level",
    location: "Remote",
    skills: ["Node.js", "Express", "MongoDB", "Docker"],
    job_link: "https://careers.google.com/jobs/",
  },
  {
    id: 4,
    postedOn: "2024-10-18",
    title: "Data Analyst",
    company: "Microsoft",
    type: "Contract",
    experience: "Entry Level",
    location: "In-Office",
    skills: ["Excel", "SQL", "Python", "Power BI"],
    job_link: "https://careers.microsoft.com/us/en",
  },
  {
    id: 5,
    postedOn: "2024-10-15",
    title: "DevOps Engineer",
    company: "Facebook",
    type: "Full Time",
    experience: "Mid Level",
    location: "Hybrid",
    skills: ["AWS", "Kubernetes", "Terraform", "CI/CD"],
    job_link: "https://www.metacareers.com/",
  },
  {
    id: 6,
    postedOn: "2024-10-12",
    title: "Cybersecurity Specialist",
    company: "Tesla",
    type: "Full Time",
    experience: "Senior Level",
    location: "Remote",
    skills: ["Network Security", "Python", "Penetration Testing", "Firewall"],
    job_link: "https://www.tesla.com/careers",
  },
  {
    id: 7,
    postedOn: "2024-10-10",
    title: "Machine Learning Engineer",
    company: "Netflix",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["Python", "TensorFlow", "Keras", "NLP"],
    job_link: "https://jobs.netflix.com/",
  },
  {
    id: 8,
    postedOn: "2024-10-08",
    title: "UX/UI Designer",
    company: "Spotify",
    type: "Part Time",
    experience: "Mid Level",
    location: "In-Office",
    skills: ["Figma", "Sketch", "Adobe XD", "User Research"],
    job_link: "https://www.spotifyjobs.com/",
  },
];
